local hit_list = {
	"Michael Holliday", "Starry Eyed", "30 January 1960",
	"Anthony Newley", "Why", "6 February 1960",
	"Adam Faith", "Poor Me", "5 March 1960",
	"Johnny Preston", "Running Bear", "19 March 1960",
	"Lonnie Donegan", "My Old Man's a Dustman", "26 March 1960",
	"Anthony Newley", "Do You Mind?", "23 April 1960",
	"The Everly Brothers", "Cathy's Clown", "30 April 1960",
	"Jimmy Jones", "Good Timin'", "2 July 1960",
	"Cliff Richard and The Shadows", "Please Don't Tease", "23 July 1960",
	"The Shadows", "Apache", "20 August 1960",
	"Ricky Valance", "Tell Laura I Love Her", "1 October 1960",
	"Roy Orbison", "Only the Lonely (Know How I Feel)", "15 October 1960",
	"Elvis Presley", "It's Now or Never", "5 November 1960",
	"Johnny Tillotson", "Poetry in Motion", "7 January 1961",
	"Elvis Presley", "Are You Lonesome Tonight?", "28 January 1961",
	"The Everly Brothers", "Walk Right Back", "4 March 1961",
	"Elvis Presley", "Wooden Heart", "15 April 1961",
	"The Allisons", "Are You Sure?", "22 April 1961",
	"The Temperance Seven", "You're Driving Me Crazy", "29 April 1961",
	"The Marcels", "Blue Moon", "6 May 1961",
	"Del Shannon", "Runaway", "24 June 1961",
	"Elvis Presley", "Surrender", "27 May 1961",
	"The Everly Brothers", "Temptation", "15 July 1961",
	"Eden Kane", "Well I Ask You", "22 July 1961",
	"Helen Shapiro", "You Don't Know", "2 September 1961",
	"John Leyton", "Johnny Remember Me", "30 September 1961",
	"Elvis Presley", "Wild in the Country", "23 September 1961",
	"The Highwaymen", "Michael (Row the Boat)", "7 October 1961",
	"Helen Shapiro", "Walkin' Back to Happiness", "14 October 1961",
	"Elvis Presley", "His Latest Flame", "11 November 1961",
	"Frankie Vaughan", "Tower of Strength", "2 December 1961",
	"Bobby Vee", "Take Good Care of My Baby", "2 December 1961",
	"Danny Williams", "Moon River", "30 December 1961",
	"Acker Bilk", "Stranger on the Shore", "6 January 1962",
	"Cliff Richard", "The Young Ones", "13 January 1962",
	"Chubby Checker", "Let's Twist Again", "24 February 1962",
	"Kenny Ball and his Jazzmen", "March of the Siamese Children", "10 March 1962",
	"The Shadows", "Wonderful Land", "17 March 1962",
	"B. Bumble and the Stingers", "Nut Rocker", "12 May 1962",
	"Elvis Presley", "Good Luck Charm", "19 May 1962",
	"Mike Sarne with Wendy Richard", "Come Outside", "23 June 1962",
	"Joe Brown and the Bruvvers", "A Picture Of You", "7 July 1962",
	"Ray Charles", "I Can't Stop Loving You", "14 July 1962",
	"Frank Ifield", "I Remember You", "21 July 1962",
	"Elvis Presley", "She's Not You", "15 September 1962",
	"The Tornados", "Telstar", "6 October 1962",
	"Frank Ifield", "Lovesick Blues", "10 November 1962",
	"Elvis Presley", "Return to Sender", "15 December 1962",
	"Cliff Richard and The Shadows", "The Next Time / Bachelor Boy", "29 December 1962",
	"The Shadows", "Dance On!", "5 January 1963",
	"Jet Harris and Tony Meehan", "Diamonds", "26 January 1963",
	"Frank Ifield", "The Wayward Wind", "23 February 1963",
	"The Beatles", "Please Please Me", "23 February 1963",
	"Cliff Richard and The Shadows", "Summer Holiday", "9 March 1963",
	"The Shadows", "Foot Tapper", "30 March 1963",
	"Gerry & The Pacemakers", "How Do You Do It?", "6 April 1963",
	"The Beatles", "From Me to You", "27 April 1963",
	"Billy J. Kramer & The Dakotas", "Do You Want to Know a Secret", "1 June 1963",
	"Gerry & The Pacemakers", "I Like It", "15 June 1963",
	"Frank Ifield", "Confessin' (That I Love You)", "13 July 1963",
	"The Searchers", "Sweets for My Sweet", "3 August 1963",
	"Billy J. Kramer & The Dakotas", "Bad to Me", "24 August 1963",
	"The Beatles", "She Loves You", "23 November 1963",
	"Brian Poole and The Tremeloes", "Do You Love Me", "5 October 1963",
	"Gerry & The Pacemakers", "You'll Never Walk Alone", "26 October 1963",
	"The Beatles", "I Want to Hold Your Hand", "7 December 1963",
	"The Dave Clark Five", "Glad All Over", "18 January 1964",
	"The Searchers", "Needles and Pins", "1 February 1964",
	"Cilla Black", "Anyone Who Had a Heart", "22 February 1964",
	"Billy J. Kramer & The Dakotas", "Little Children", "21 March 1964",
	"The Beatles", "Can't Buy Me Love", "28 March 1964",
	"Peter & Gordon", "A World Without Love", "25 April 1964",
	"The Searchers", "Don't Throw Your Love Away", "9 May 1964",
	"The Four Pennies", "Juliet", "16 May 1964",
	"Cilla Black", "You're My World (Il Mio Mondo)", "30 May 1964",
	"Roy Orbison", "It's Over", "20 June 1964",
	"The Animals", "House of the Rising Sun", "4 July 1964",
	"The Beatles", "A Hard Day's Night", "18 July 1964",
	"Manfred Mann", "Do Wah Diddy Diddy", "15 August 1964",
	"The Honeycombs", "Have I the Right?", "29 August 1964",
	"The Kinks", "You Really Got Me", "12 September 1964",
	"Herman's Hermits", "I'm Into Something Good", "19 September 1964",
	"Roy Orbison", "Oh, Pretty Woman", "10 October 1964",
	"Sandie Shaw", "(There's) Always Something There to Remind Me", "31 October 1964",
	"The Supremes", "Baby Love", "14 November 1964",
	"The Rolling Stones", "Little Red Rooster", "21 November 1964",
	"The Beatles", "I Feel Fine", "5 December 1964",
	"Georgie Fame", "Yeh Yeh", "16 January 1965",
	"The Moody Blues", "Go Now", "23 January 1965",
	"The Righteous Brothers", "You've Lost That Lovin' Feelin'", "6 February 1965",
	"The Kinks", "Tired of Waiting for You", "13 February 1965",
	"The Seekers", "I'll Never Find Another You", "20 February 1965",
	"Tom Jones", "It's Not Unusual", "6 March 1965",
	"The Rolling Stones", "The Last Time", "13 March 1965",
	"The Yardbirds", "For Your Love", "10 April 1965",
	"Cliff Richard", "The Minute You're Gone", "10 April 1965",
	"The Beatles", "Ticket to Ride", "17 April 1965",
	"Jackie Trent", "Where Are You Now (My Love)", "22 May 1965",
	"Sandie Shaw", "Long Live Love", "29 May 1965",
	"The Everly Brothers", "The Price of Love", "12 June 1965",
	"Elvis Presley", "Crying in the Chapel", "19 June 1965",
	"The Hollies", "I'm Alive", "3 July 1965",
	"The Byrds", "Mr. Tambourine Man", "17 July 1965",
	"The Beatles", "Help!", "31 July 1965",
	"Sonny & Cher", "I Got You Babe", "28 August 1965",
	"The Rolling Stones", "(I Can't Get No) Satisfaction", "4 September 1965",
	"Ken Dodd", "Tears", "25 September 1965",
	"The Rolling Stones", "Get Off of My Cloud", "6 November 1965",
	"Len Barry", "1-2-3", "27 November 1965",
	"The Seekers", "The Carnival Is Over", "4 December 1965",
	"The Beatles", "Day Tripper / We Can Work It Out", "11 December 1965",
	"The Spencer Davis Group", "Keep On Running", "15 January 1966",
	"The Overlanders", "Michelle", "5 February 1966",
	"Nancy Sinatra", "These Boots Are Made for Walkin'", "12 February 1966",
	"The Rolling Stones", "19th Nervous Breakdown", "19 February 1966",
	"The Hollies", "I Can't Let Go", "12 March 1966",
	"The Walker Brothers", "The Sun Ain't Gonna Shine Anymore", "19 March 1966",
	"The Spencer Davis Group", "Somebody Help Me", "16 April 1966",
	"Dusty Springfield", "You Don't Have to Say You Love Me", "23 April 1966",
	"Manfred Mann", "Pretty Flamingo", "7 May 1966",
	"The Rolling Stones", "Paint It, Black", "28 May 1966",
	"Frank Sinatra", "Strangers in the Night", "4 June 1966",
	"The Beatles", "Paperback Writer", "25 June 1966",
	"The Kinks", "Sunny Afternoon", "9 July 1966",
	"Chris Farlowe", "Out of Time", "23 July 1966",
	"The Troggs", "With a Girl Like You", "6 August 1966",
	"The Beatles", "Yellow Submarine / Eleanor Rigby", "20 August 1966",
	"Small Faces", "All or Nothing", "17 September 1966",
	"Jim Reeves", "Distant Drums", "24 September 1966",
	"Four Tops", "Reach Out I'll Be There", "29 October 1966",
	"The Beach Boys", "Good Vibrations", "19 November 1966",
	"Tom Jones", "Green, Green Grass of Home", "3 December 1966",
	"The Monkees", "I'm a Believer", "21 January 1967",
	"Petula Clark", "This Is My Song", "18 February 1967",
	"Engelbert Humperdinck", "Release Me", "4 March 1967",
	"Nancy Sinatra and Frank Sinatra", "Somethin' Stupid", "15 April 1967",
	"Sandie Shaw", "Puppet on a String", "22 April 1967",
	"The Tremeloes", "Silence Is Golden", "20 May 1967",
	"Procol Harum", "A Whiter Shade of Pale", "10 June 1967",
	"The Beatles", "All You Need Is Love", "15 July 1967",
	"Scott McKenzie", "San Francisco (Be Sure to Wear Flowers in Your Hair)", "12 August 1967",
	"Engelbert Humperdinck", "The Last Waltz", "9 September 1967",
	"Bee Gees", "Massachusetts", "21 October 1967",
	"The Foundations", "Baby Now That I've Found You", "11 November 1967",
	"Long John Baldry", "Let the Heartaches Begin", "2 December 1967",
	"The Beatles", "Hello, Goodbye", "9 December 1967",
	"Georgie Fame", "The Ballad of Bonnie and Clyde", "20 January 1968",
	"Love Affair", "Everlasting Love", "27 January 1968",
	"Manfred Mann", "Mighty Quinn", "17 February 1968",
	"Esther and Abi Ofarim", "Cinderella Rockefella", "2 March 1968",
	"The Beatles", "Lady Madonna", "30 March 1968",
	"Cliff Richard", "Congratulations", "13 April 1968",
	"Louis Armstrong", "What a Wonderful World", "20 April 1968",
	"Gary Puckett & The Union Gap", "Young Girl", "18 May 1968",
	"The Rolling Stones", "Jumpin' Jack Flash", "22 June 1968",
	"The Equals", "Baby Come Back", "6 July 1968",
	"Tommy James and the Shondells", "Mony Mony", "27 July 1968",
	"Tom Jones", "Help Yourself", "24 August 1968",
	"Bee Gees", "I've Gotta Get a Message to You", "7 September 1968",
	"The Beatles", "Hey Jude", "14 September 1968",
	"Mary Hopkin", "Those Were the Days", "5 October 1968",
	"Joe Cocker", "With a Little Help from My Friends", "9 November 1968",
	"Hugo Montenegro", "The Good, the Bad and the Ugly", "16 November 1968",
	"Barry Ryan", "Eloise", "23 November 1968",
	"The Scaffold", "Lily the Pink", "7 December 1968",
	"Marmalade", "Ob-La-Di, Ob-La-Da", "11 January 1969",
	"Fleetwood Mac", "Albatross", "25 January 1969",
	"The Move", "Blackberry Way", "15 February 1969",
	"Amen Corner", "(If Paradise) Is Half as Nice", "22 February 1969",
	"Peter Sarstedt", "Where Do You Go To (My Lovely)?", "1 March 1969",
	"Marvin Gaye", "I Heard It Through the Grapevine", "29 March 1969",
	"Desmond Dekker & The Aces", "Israelites", "19 April 1969",
	"The Beatles with Billy Preston", "Get Back", "3 May 1969",
	"Tommy Roe", "Dizzy", "7 June 1969",
	"The Beatles", "The Ballad of John and Yoko", "21 June 1969",
	"Thunderclap Newman", "Something in the Air", "5 July 1969",
	"Elvis Presley", "In the Ghetto", "19 July 1969",
	"The Rolling Stones", "Honky Tonk Women", "26 July 1969",
	"Zager and Evans", "In The Year 2525 (Exordium and Terminus)", "30 August 1969",
	"Creedence Clearwater Revival", "Bad Moon Rising", "20 September 1969",
	"Bobbie Gentry", "I'll Never Fall in Love Again", "11 October 1969",
	"The Archies", "Sugar, Sugar", "22 November 1969",
	"Fleetwood Mac", "Oh Well", "15 November 1969",
	"Stevie Wonder", "Yester-Me, Yester-You, Yesterday", "6 December 1969",
	"Kenny Rogers and The First Edition", "Ruby, Don't Take Your Love to Town", "13 December 1969",
	"Rolf Harris", "Two Little Boys", "20 December 1969",
	"Marmalade", "Reflections of My Life", "31 January 1970",
	"Edison Lighthouse", "Love Grows (Where My Rosemary Goes)", "7 February 1970",
	"The Jackson 5", "I Want You Back", "28 February 1970",
	"Lee Marvin", "Wand'rin' Star", "7 March 1970",
	"Simon & Garfunkel", "Bridge over Troubled Water", "28 March 1970",
	"Norman Greenbaum", "Spirit in the Sky", "25 April 1970",
	"England World Cup Squad 70", "Back Home", "9 May 1970",
	"The Moody Blues", "Question", "30 May 1970",
	"Christie", "Yellow River", "6 June 1970",
	"Mungo Jerry", "In the Summertime", "13 June 1970",
	"Free", "All Right Now", "11 July 1970",
	"The Kinks", "Lola", "1 August 1970",
	"Elvis Presley", "The Wonder of You", "8 August 1970",
	"Smokey Robinson and The Miracles", "The Tears of a Clown", "29 August 1970",
	"Freda Payne", "Band of Gold", "26 September 1970",
	"Deep Purple", "Black Night", "31 October 1970",
	"Matthews' Southern Comfort", "Woodstock", "7 November 1970",
	"Jimi Hendrix Experience", "Voodoo Chile", "28 November 1970",
	"Dave Edmunds's Rockpile", "I Hear You Knocking", "5 December 1970",
	"McGuinness Flint", "When I'm Dead and Gone", "26 December 1970",
	"Clive Dunn", "Grandad", "2 January 1971",
	"George Harrison", "My Sweet Lord", "30 January 1971",
	"Mungo Jerry", "Baby Jump", "13 March 1971",
	"Paul McCartney", "Another Day", "20 March 1971",
	"T. Rex", "Hot Love", "27 March 1971",
	"Dave and Ansel Collins", "Double Barrel", "1 May 1971",
	"The Rolling Stones", "Brown Sugar", "15 May 1971",
	"Dawn", "Knock Three Times", "22 May 1971",
	"Free", "My Brother Jake", "12 June 1971",
	"Tony Christie", "I Did What I Did for Maria", "19 June 1971",
	"Middle of the Road", "Chirpy Chirpy Cheep Cheep", "26 June 1971",
	"T. Rex", "Get It On", "31 July 1971",
	"The New Seekers", "Never Ending Song of Love", "21 August 1971",
	"Diana Ross", "I'm Still Waiting", "28 August 1971",
	"The Tams", "Hey Girl Don't Bother Me", "18 September 1971",
	"Rod Stewart", "Maggie May", "2 October 1971",
	"Slade", "Coz I Luv You", "13 November 1971",
	"Benny Hill", "Ernie (The Fastest Milkman in the West)", "4 December 1971",
	"The New Seekers", "I'd Like to Teach the World to Sing (In Perfect Harmony)", "8 January 1972",
	"America", "A Horse with No Name", "5 February 1972",
	"T. Rex", "Telegram Sam", "12 February 1972",
	"Chicory Tip", "Son of My Father", "19 February 1972",
	"Don McLean", "American Pie", "4 March 1972",
	"Nilsson", "Without You", "11 March 1972",
	"Royal Scots Dragoon Guards", "Amazing Grace", "22 April 1972",
	"T.Rex", "Metal Guru", "20 May 1972",
	"Don McLean", "Vincent", "17 June 1972",
	"Slade", "Take Me Bak 'Ome", "8 July 1972",
	"Donny Osmond", "Puppy Love", "15 July 1972",
	"Alice Cooper", "School's Out", "12 August 1972",
	"Rod Stewart", "You Wear It Well", "2 September 1972",
	"Slade", "Mama Weer All Crazee Now", "16 September 1972",
	"T. Rex", "Children of the Revolution", "30 September 1972",
	"David Cassidy", "How Can I Be Sure", "7 October 1972",
	"Lieutenant Pigeon", "Mouldy Old Dough", "14 October 1972",
	"Gilbert O'Sullivan", "Clair", "11 November 1972",
	"Chuck Berry", "My Ding-a-Ling", "25 November 1972",
	"Slade", "Gudbuy T' Jane", "16 December 1972",
	"Little Jimmy Osmond", "Long Haired Lover from Liverpool", "23 December 1972",
	"David Bowie", "The Jean Genie", "20 January 1973",
	"Sweet", "Blockbuster", "27 January 1973",
	"Strawbs", "Part of the Union", "24 February 1973",
	"Slade", "Cum On Feel the Noize", "10 March 1973",
	"Donny Osmond", "The Twelfth of Never", "31 March 1973",
	"Gilbert O'Sullivan", "Get Down", "14 April 1973",
	"Dawn featuring Tony Orlando", "Tie a Yellow Ribbon Round the Ole Oak Tree", "21 April 1973",
	"Wizzard", "See My Baby Jive", "26 May 1973",
	"Suzi Quatro", "Can the Can", "9 June 1973",
	"10cc", "Rubber Bullets", "30 June 1973",
	"Slade", "Skweeze Me Pleeze Me", "7 July 1973",
	"Peters and Lee", "Welcome Home", "21 July 1973",
	"Gary Glitter", "I'm the Leader of the Gang (I Am!)", "4 August 1973",
	"Donny Osmond", "Young Love", "1 September 1973",
	"Wizzard", "Angel Fingers (A Teen Ballad)", "15 September 1973",
	"David Essex", "Rock On", "22 September 1973",
	"The Sweet", "The Ballroom Blitz", "29 September 1973",
	"Simon Park Orchestra", "Eye Level (Theme From The Thames TV Series 'Van Der Valk')", "6 October 1973",
	"David Cassidy", "The Puppy Song / Daydreamer", "3 November 1973",
	"The Osmonds", "Let Me In", "17 November 1973",
	"Gary Glitter", "I Love You Love Me Love", "24 November 1973",
	"Slade", "Merry Xmas Everybody", "22 December 1973",
	"New Seekers feat. Lyn Paul", "You Won't Find Another Fool Like Me", "5 January 1974",
	"Leo Sayer", "The Show Must Go On", "19 January 1974",
	"Sweet", "Teenage Rampage", "26 January 1974",
	"Mud", "Tiger Feet", "2 February 1974",
	"Suzi Quatro", "Devil Gate Drive", "23 February 1974",
	"Alvin Stardust", "Jealous Mind", "9 March 1974",
	"Paper Lace", "Billy Don't Be a Hero", "23 March 1974",
	"Terry Jacks", "Seasons in the Sun", "13 April 1974",
	"Mud", "The Cat Crept In", "27 April 1974",
	"ABBA", "Waterloo", "4 May 1974",
	"The Rubettes", "Sugar Baby Love", "18 May 1974",
	"Ray Stevens", "The Streak", "15 June 1974",
	"Gary Glitter", "Always Yours", "29 June 1974",
	"Charles Aznavour", "She", "6 July 1974",
	"George McCrae", "Rock Your Baby", "27 July 1974",
	"The Three Degrees", "When Will I See You Again", "17 August 1974",
	"The Osmonds", "Love Me for a Reason", "7 September 1974",
	"Carl Douglas", "Kung Fu Fighting", "21 September 1974",
	"Peter Shelley", "Gee Baby", "19 October 1974",
	"Ken Boothe", "Everything I Own", "26 October 1974",
	"David Essex", "Gonna Make You a Star", "9 November 1974",
	"Barry White", "You're the First, the Last, My Everything", "14 December 1974",
	"Mud", "Lonely This Christmas", "21 December 1974",
	"Ralph McTell", "Streets of London", "11 January 1975",
	"Status Quo", "Down Down", "25 January 1975",
	"The Tymes", "Ms Grace", "1 February 1975",
	"Pilot", "January", "8 February 1975",
	"The Carpenters", "Please Mr. Postman", "22 February 1975",
	"Steve Harley & Cockney Rebel", "Make Me Smile (Come Up and See Me)", "1 March 1975",
	"Telly Savalas", "If", "8 March 1975",
	"Bay City Rollers", "Bye Bye Baby", "22 March 1975",
	"Bobby Goldsboro", "Honey", "3 May 1975",
	"Minnie Riperton", "Lovin' You", "10 May 1975",
	"Tammy Wynette", "Stand by Your Man", "17 May 1975",
	"Windsor Davies and Don Estelle", "Whispering Grass", "21 June 1975",
	"Showaddywaddy", "Three Steps to Heaven", "14 June 1975",
	"10cc", "I'm Not in Love", "28 June 1975",
	"Johnny Nash", "Tears on My Pillow", "12 July 1975",
	"Bay City Rollers", "Give a Little Love", "26 July 1975",
	"Typically Tropical", "Barbados", "2 August 1975",
	"The Stylistics", "Can't Give You Anything (But My Love)", "16 August 1975",
	"Rod Stewart", "Sailing", "30 August 1975",
	"Leo Sayer", "Moonlighting", "27 September 1975",
	"David Essex", "Hold Me Close", "4 October 1975",
	"Art Garfunkel", "I Only Have Eyes for You", "25 October 1975",
	"David Bowie", "Space Oddity", "8 November 1975",
	"Billy Connolly", "D.I.V.O.R.C.E.", "22 November 1975",
	"Hot Chocolate", "You Sexy Thing", "29 November 1975",
	"Queen", "Bohemian Rhapsody", "6 December 1975",
	"Sailor", "A Glass of Champagne", "24 January 1976",
	"ABBA", "Mamma Mia", "31 January 1976",
	"Slik", "Forever and Ever", "14 February 1976",
	"The Four Seasons", "December, 1963 (Oh, What a Night)", "21 February 1976",
	"Tina Charles", "I Love to Love (But My Baby Loves to Dance)", "6 March 1976",
	"Brotherhood of Man", "Save Your Kisses for Me", "27 March 1976",
	"ABBA", "Fernando", "1 May 1976",
	"J. J. Barrie", "No Charge", "12 June 1976",
	"Wings", "Silly Love Songs", "19 June 1976",
	"Real Thing", "You to Me Are Everything", "26 June 1976",
	"Candi Staton", "Young Hearts Run Free", "10 July 1976",
	"Demis Roussos", "The Roussos Phenomenon EP", "17 July 1976",
	"Elton John & Kiki Dee", "Don't Go Breaking My Heart", "24 July 1976",
	"ABBA", "Dancing Queen", "11 September 1976",
	"Pussycat", "Mississippi", "16 October 1976",
	"Chicago", "If You Leave Me Now", "6 November 1976",
	"Showaddywaddy", "Under the Moon of Love", "4 December 1976",
	"Johnny Mathis", "When a Child Is Born", "25 December 1976",
	"David Soul", "Don't Give Up on Us", "5 February 1977",
	"Julie Covington", "Don't Cry for Me Argentina", "12 February 1977",
	"Leo Sayer", "When I Need You", "26 February 1977",
	"The Manhattan Transfer", "Chanson D'Amour", "12 March 1977",
	"ABBA", "Knowing Me, Knowing You", "26 March 1977",
	"Deniece Williams", "Free", "7 May 1977",
	"Rod Stewart", "I Don't Want to Talk About It / The First Cut Is the Deepest", "28 May 1977",
	"Sex Pistols", "God Save the Queen", "18 June 1977",
	"The Jacksons", "Show You the Way to Go", "25 June 1977",
	"Hot Chocolate", "So You Win Again", "9 July 1977",
	"Boney M.", "Ma Baker", "16 July 1977",
	"Donna Summer", "I Feel Love", "23 July 1977",
	"Brotherhood of Man", "Angelo", "27 August 1977",
	"Elvis Presley", "Way Down", "1 October 1977",
	"Space", "Magic Fly", "10 September 1977",
	"David Soul", "Silver Lady", "15 October 1977",
	"Baccara", "Yes Sir, I Can Boogie", "5 November 1977",
	"Rod Stewart", "You're in My Heart", "29 October 1977",
	"ABBA", "The Name of the Game", "12 November 1977",
	"Status Quo", "Rockin' All Over the World", "26 November 1977",
	"Wings", "Mull of Kintyre", "3 December 1977",
	"Althea & Donna", "Uptown Top Ranking", "4 February 1978",
	"ABBA", "Take a Chance on Me", "18 February 1978",
	"Kate Bush", "Wuthering Heights", "11 March 1978",
	"Blondie", "Denis", "1 April 1978",
	"Showaddywaddy", "I Wonder Why", "15 April 1978",
	"Bee Gees", "Night Fever", "22 April 1978",
	"Boney M.", "Rivers of Babylon", "20 May 1978",
	"John Travolta and Olivia Newton-John", "You're the One That I Want", "17 June 1978",
	"Commodores", "Three Times a Lady", "26 August 1978",
	"10cc", "Dreadlock Holiday", "23 September 1978",
	"John Travolta and Olivia Newton-John", "Summer Nights", "7 October 1978",
	"The Boomtown Rats", "Rat Trap", "18 November 1978",
	"Rod Stewart", "Da Ya Think I'm Sexy?", "9 December 1978",
	"Boney M.", "Mary's Boy Child ? Oh My Lord", "16 December 1978",
	"Village People", "Y.M.C.A.", "6 January 1979",
	"Ian Dury", "Hit Me with Your Rhythm Stick", "27 January 1979",
	"Blondie", "Heart of Glass", "24 February 1979",
	"ABBA", "Chiquitita", "17 February 1979",
	"Bee Gees", "Tragedy", "10 March 1979",
	"Elvis Costello", "Oliver's Army", "17 March 1979",
	"Gloria Gaynor", "I Will Survive", "24 March 1979",
	"Village People", "In the Navy", "7 April 1979",
	"Art Garfunkel", "Bright Eyes", "26 May 1979",
	"M", "Pop Muzik", "19 May 1979",
	"Blondie", "Sunday Girl", "2 June 1979",
	"Roxy Music", "Dance Away", "9 June 1979",
	"Anita Ward", "Ring My Bell", "16 June 1979",
	"Tubeway Army", "Are 'Friends' Electric?", "28 July 1979",
	"Janet Kay", "Silly Games", "21 July 1979",
	"The Boomtown Rats", "I Don't Like Mondays", "4 August 1979",
	"Cliff Richard", "We Don't Talk Anymore", "1 September 1979",
	"Gary Numan", "Cars", "22 September 1979",
	"The Police", "Message in a Bottle", "6 October 1979",
	"The Buggles", "Video Killed the Radio Star", "20 October 1979",
	"Lena Martell", "One Day at a Time", "3 November 1979",
	"Dr. Hook", "When You're in Love with a Beautiful Woman", "10 November 1979",
	"The Police", "Walking on the Moon", "8 December 1979",
	"Pink Floyd", "Another Brick in the Wall (Part II)", "15 December 1979",
	"Pretenders", "Brass in Pocket", "19 January 1980",
	"Madness", "My Girl", "2 February 1980",
	"The Specials", "The Special A.K.A. Live!", "9 February 1980",
	"Kenny Rogers", "Coward of the County", "16 February 1980",
	"Blondie", "Atomic", "1 March 1980",
	"Fern Kinney", "Together We Are Beautiful", "22 March 1980",
	"The Jam", "Going Underground", "29 March 1980",
	"Liquid Gold", "Dance Yourself Dizzy", "12 April 1980",
	"Blondie", "Call Me", "26 April 1980",
	"Dexy's Midnight Runners", "Geno", "10 May 1980",
	"Johnny Logan", "What's Another Year", "17 May 1980",
	"Hot Chocolate", "No Doubt About It", "31 May 1980",
	"M*A*S*H", "Theme from M*A*S*H (Suicide is Painless)", "7 June 1980",
	"Lipps Inc", "Funkytown", "21 June 1980",
	"Don McLean", "Crying", "28 June 1980",
	"Olivia Newton-John and the Electric Light Orchestra", "Xanadu", "12 July 1980",
	"Odyssey", "Use It Up and Wear It Out", "2 August 1980",
	"Diana Ross", "Upside Down", "9 August 1980",
	"ABBA", "The Winner Takes It All", "16 August 1980",
	"David Bowie", "Ashes to Ashes", "30 August 1980",
	"The Jam", "Start!", "13 September 1980",
	"Randy Crawford", "One Day I'll Fly Away", "20 September 1980",
	"The Police", "Don't Stand So Close to Me", "4 October 1980",
	"Barbra Streisand", "Woman in Love", "1 November 1980",
	"Blondie", "The Tide Is High", "22 November 1980",
	"ABBA", "Super Trouper", "6 December 1980",
	"Jona Lewie", "Stop the Cavalry", "20 December 1980",
	"John Lennon", "(Just Like) Starting Over", "3 January 1981",
	"John Lennon", "Imagine", "10 January 1981",
	"Phil Collins", "In the Air Tonight", "7 February 1981",
	"Ultravox", "Vienna", "21 February 1981",
	"Joe Dolce Music Theatre", "Shaddap You Face", "28 February 1981",
	"Roxy Music", "Jealous Guy", "14 March 1981",
	"Shakin' Stevens", "This Ole House", "28 March 1981",
	"Bucks Fizz", "Making Your Mind Up", "18 April 1981",
	"Ennio Morricone", "Chi Mai (Theme from The Life and Times of David Lloyd George)", "2 May 1981",
	"Starsound", "Stars on 45", "9 May 1981",
	"Adam and the Ants", "Stand and Deliver", "16 May 1981",
	"Smokey Robinson", "Being with You", "13 June 1981",
	"Michael Jackson", "One Day In Your Life", "27 June 1981",
	"The Specials", "Ghost Town", "18 July 1981",
	"Spandau Ballet", "Chant No. 1 (I Don't Need This Pressure On)", "1 August 1981",
	"Shakin' Stevens", "Green Door", "22 August 1981",
	"Stevie Wonder", "Happy Birthday", "15 August 1981",
	"Aneka", "Japanese Boy", "5 September 1981",
	"Soft Cell", "Tainted Love", "12 September 1981",
	"Adam and the Ants", "Prince Charming", "19 September 1981",
	"Dave Stewart and Barbara Gaskin", "It's My Party", "24 October 1981",
	"Altered Images", "Happy Birthday", "7 November 1981",
	"The Police", "Every Little Thing She Does Is Magic", "14 November 1981",
	"Queen and David Bowie", "Under Pressure", "28 November 1981",
	"Julio Iglesias", "Begin The Beguine (Volver A Empezar)", "12 December 1981",
	"The Human League", "Don't You Want Me", "9 January 1982",
	"ABBA", "One of Us", "2 January 1982",
	"Bucks Fizz", "The Land of Make Believe", "16 January 1982",
	"Kraftwerk", "Computer Love / The Model", "30 January 1982",
	"The Jam", "Town Called Malice", "20 February 1982",
	"Tight Fit", "The Lion Sleeps Tonight", "13 March 1982",
	"Goombay Dance Band", "Seven Tears", "3 April 1982",
	"Bucks Fizz", "My Camera Never Lies", "17 April 1982",
	"Paul McCartney and Stevie Wonder", "Ebony and Ivory", "1 May 1982",
	"Ph.D.", "I Won't Let You Down", "15 May 1982",
	"Nicole", "A Little Peace", "22 May 1982",
	"Adam Ant", "Goody Two Shoes", "19 June 1982",
	"Madness", "House of Fun", "5 June 1982",
	"Charlene", "I've Never Been to Me", "3 July 1982",
	"Captain Sensible", "Happy Talk", "10 July 1982",
	"Steve Miller Band", "Abracadabra", "17 July 1982",
	"Irene Cara", "Fame", "24 July 1982",
	"Dexy's Midnight Runners", "Come On Eileen", "7 August 1982",
	"Survivor", "Eye of the Tiger", "4 September 1982",
	"Dire Straits", "Private Investigations", "25 September 1982",
	"The Jam", "The Bitterest Pill", "2 October 1982",
	"Musical Youth", "Pass the Dutchie", "9 October 1982",
	"Culture Club", "Do You Really Want to Hurt Me", "23 October 1982",
	"Eddy Grant", "I Don't Wanna Dance", "13 November 1982",
	"Dionne Warwick", "Heartbreaker", "27 November 1982",
	"The Human League", "Mirror Man", "4 December 1982",
	"The Jam", "Beat Surrender", "18 December 1982",
	"Culture Club", "Time (Clock of the Heart)", "25 December 1982",
	"Ren?e and Renato", "Save Your Love", "8 January 1983",
	"Phil Collins", "You Can't Hurry Love", "15 January 1983",
	"Men at Work", "Down Under", "29 January 1983",
	"Kajagoogoo", "Too Shy", "19 February 1983",
	"Michael Jackson", "Billie Jean", "5 March 1983",
	"Bonnie Tyler", "Total Eclipse of the Heart", "19 March 1983",
	"Duran Duran", "Is There Something I Should Know?", "2 April 1983",
	"David Bowie", "Let's Dance", "16 April 1983",
	"Spandau Ballet", "True", "7 May 1983",
	"New Edition", "Candy Girl", "4 June 1983",
	"The Police", "Every Breath You Take", "2 July 1983",
	"David Bowie", "China Girl", "25 June 1983",
	"Rod Stewart", "Baby Jane", "9 July 1983",
	"Paul Young", "Wherever I Lay My Hat (That's My Home)", "16 July 1983",
	"KC and the Sunshine Band", "Give It Up", "20 August 1983",
	"Spandau Ballet", "Gold", "27 August 1983",
	"UB40", "Red Red Wine", "10 September 1983",
	"Culture Club", "Karma Chameleon", "1 October 1983",
	"Billy Joel", "Uptown Girl", "12 November 1983",
	"The Assembly", "Never Never", "3 December 1983",
	"Paul Young", "Love of the Common People", "10 December 1983",
	"The Flying Pickets", "Only You", "17 December 1983",
	"Paul McCartney", "Pipes of Peace", "21 January 1984",
	"Frankie Goes to Hollywood", "Relax", "25 February 1984",
	"Queen", "Radio Ga Ga", "18 February 1984",
	"Nena", "99 Red Balloons", "3 March 1984",
	"Lionel Richie", "Hello", "31 March 1984",
	"Phil Collins", "Against All Odds (Take a Look at Me Now)", "5 May 1984",
	"Duran Duran", "The Reflex", "12 May 1984",
	"The Pointer Sisters", "Automatic", "26 May 1984",
	"Wham!", "Wake Me Up Before You Go-Go", "9 June 1984",
	"Frankie Goes to Hollywood", "Two Tribes", "23 June 1984",
	"George Michael", "Careless Whisper", "18 August 1984",
	"Stevie Wonder", "I Just Called to Say I Love You", "8 September 1984",
	"Culture Club", "The War Song", "20 October 1984",
	"Wham!", "Freedom", "27 October 1984",
	"Chaka Khan", "I Feel for You", "17 November 1984",
	"Jim Diamond", "I Should Have Known Better", "8 December 1984",
	"Band Aid", "Do They Know It's Christmas?", "5 January 1985",
	"Wham!", "Everything She Wants / Last Christmas", "19 January 1985",
	"Foreigner", "I Want to Know What Love Is", "26 January 1985",
	"Elaine Paige and Barbara Dickson", "I Know Him So Well", "23 February 1985",
	"King", "Love and Pride", "16 February 1985",
	"Dead or Alive", "You Spin Me Round (Like a Record)", "9 March 1985",
	"Philip Bailey (duet with Phil Collins)", "Easy Lover", "23 March 1985",
	"Frankie Goes to Hollywood", "Welcome to the Pleasuredome", "13 April 1985",
	"Tears for Fears", "Everybody Wants to Rule the World", "20 April 1985",
	"Phyllis Nelson", "Move Closer", "11 May 1985",
	"Paul Hardcastle", "19", "18 May 1985",
	"The Crowd", "You'll Never Walk Alone", "22 June 1985",
	"Madonna", "Crazy for You", "29 June 1985",
	"Sister Sledge", "Frankie", "6 July 1985",
	"Eurythmics", "There Must Be an Angel (Playing with My Heart)", "27 July 1985",
	"Madonna", "Into the Groove", "10 August 1985",
	"UB40 and Chrissie Hynde", "I Got You Babe", "7 September 1985",
	"David Bowie and Mick Jagger", "Dancing in the Street", "14 September 1985",
	"Midge Ure", "If I Was", "5 October 1985",
	"Jennifer Rush", "The Power Of Love", "9 November 1985",
	"a-ha", "Take on Me", "2 November 1985",
	"Elton John", "Nikita", "16 November 1985",
	"Feargal Sharkey", "A Good Heart", "23 November 1985",
	"Wham!", "I'm Your Man", "7 December 1985",
	"Whitney Houston", "Saving All My Love for You", "4 January 1986",
	"Pet Shop Boys", "West End Girls", "11 January 1986",
	"a-ha", "The Sun Always Shines on T.V.", "25 January 1986",
	"Billy Ocean", "When the Going Gets Tough, the Tough Get Going", "15 February 1986",
	"Diana Ross", "Chain Reaction", "15 March 1986",
	"David Bowie", "Absolute Beginners", "29 March 1986",
	"Cliff Richard and The Young Ones", "Living Doll", "5 April 1986",
	"George Michael", "A Different Corner", "26 April 1986",
	"Falco", "Rock Me Amadeus", "17 May 1986",
	"Spitting Image", "The Chicken Song", "24 May 1986",
	"Doctor and the Medics", "Spirit in the Sky", "7 June 1986",
	"Wham!", "The Edge of Heaven", "5 July 1986",
	"Madonna", "Papa Don't Preach", "12 July 1986",
	"Chris de Burgh", "The Lady in Red", "2 August 1986",
	"Boris Gardiner", "I Want to Wake Up with You", "23 August 1986",
	"The Communards", "Don't Leave Me This Way", "13 September 1986",
	"Madonna", "True Blue", "18 October 1986",
	"Nick Berry", "Every Loser Wins", "25 October 1986",
	"Berlin", "Take My Breath Away", "15 November 1986",
	"Europe", "The Final Countdown", "6 December 1986",
	"The Housemartins", "Caravan of Love", "3 January 1987",
	"Jackie Wilson", "Reet Petite (The Sweetest Girl in Town)", "10 January 1987",
	"Robbie Nevil", "C'est La Vie", "31 January 1987",
	"Aretha Franklin and George Michael", "I Knew You Were Waiting (For Me)", "7 February 1987",
	"Ben E. King", "Stand by Me", "28 February 1987",
	"Boy George", "Everything I Own", "21 March 1987",
	"Mel and Kim", "Respectable", "28 March 1987",
	"Ferry Aid", "Let It Be", "11 April 1987",
	"Madonna", "La Isla Bonita", "25 April 1987",
	"Starship", "Nothing's Gonna Stop Us Now", "16 May 1987",
	"Whitney Houston", "I Wanna Dance with Somebody (Who Loves Me)", "6 June 1987",
	"The Firm", "Star Trekkin'", "27 June 1987",
	"Pet Shop Boys", "It's a Sin", "11 July 1987",
	"Madonna", "Who's That Girl", "1 August 1987",
	"Los Lobos", "La Bamba", "8 August 1987",
	"Michael Jackson", "I Just Can't Stop Loving You", "22 August 1987",
	"Rick Astley", "Never Gonna Give You Up", "5 September 1987",
	"M|A|R|R|S", "Pump Up the Volume", "3 October 1987",
	"Abigail Mead & Nigel Goulding", "Full Metal Jacket", "17 October 1987",
	"Bee Gees", "You Win Again", "14 November 1987",
	"George Michael", "Faith", "7 November 1987",
	"T'Pau", "China in Your Hand", "21 November 1987",
	"Rick Astley", "When I Fall in Love", "19 December 1987",
	"Pet Shop Boys", "Always on My Mind", "9 January 1988",
	"Belinda Carlisle", "Heaven Is a Place on Earth", "23 January 1988",
	"Tiffany", "I Think We're Alone Now", "6 February 1988",
	"Kylie Minogue", "I Should Be So Lucky", "20 February 1988",
	"Bomb the Bass", "Beat Dis", "5 March 1988",
	"Rick Astley", "Together Forever", "19 March 1988",
	"Aswad", "Don't Turn Around", "26 March 1988",
	"Pet Shop Boys", "Heart", "16 April 1988",
	"S-Express", "Theme from S-Express", "30 April 1988",
	"Fairground Attraction", "Perfect", "14 May 1988"
}

local function rand()
	return math.floor(math.random() * #hit_list / 3) * 3 + 1
end

local function answer(n)
	print(L.nick ..': "'.. hit_list[n + 1] ..'" by '.. hit_list[n] .." (".. hit_list[n + 2] ..")")
end

function getHit(year)
	if not year then 
		answer(rand())
		return
	end
	year = tostring(year)
	
	if string.len(year) == 2 then
		year = "19".. year
	end
	
	local year_i = tonumber(year)
	
	if not year_i or not (year_i >= 1960 and year_i <= 1988) then
		print(L.nick ..": There are only songs from year 1960 to 1988.")
		return
	end
	
	for tries = 0, 400 do
		local n = rand()
		if string.sub(hit_list[n + 2], -4) == year then
			answer(n)
			return
		end
	end
	print(L.nick ..": No number 1 hit found.. retry?")
end